global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'monitor'

scrape_configs:
  - job_name: 'consul'
    consul_sd_configs:
      - server: 'consul:8500'
        services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,metric,.*
        action: keep
      - source_labels: [__meta_consul_service]
        target_label: job 
